# Generated by Django 5.2.4 on 2025-07-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stop",
            options={"ordering": ["sequence"]},
        ),
        migrations.AddField(
            model_name="stop",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
